# Generated by Django 3.1.4 on 2020-12-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='unset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
